### ISSUE TITLE
Calculating BASE SHA on master branch

### ISSUE THREAD

**Issue by vikaskumr** [nrwl/nx-orb#47]
## Orb version:

nrwl/nx@1.6.1

## What happened:

I used `nx/set-shas` in my circleci deployment but by default by main branch is `master` and in circleci I always get `Base SHA` as null and the below error.

```
undefined:1
{:message "Project not found"}
 ^

SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/circleci/project/index.js:138:35)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

## Expected behavior:

Ideally it should return the `Base SHA` and `Head SHA`

## Additional Information:
Here is the output of the Circleci 

```
undefined:1
{:message "Project not found"}
 ^

SyntaxError: Unexpected token : in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/circleci/project/index.js:138:35)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

Base SHA


Head SHA
4d59078a4a8c8e82c4a47a1258fa74064a1be522


NX_BASE and NX_HEAD environment variables have been set for the current Job
CircleCI received exit code 0
```
Any assistance you can provide is much appreciated. Thanks!

**Comment by meeroslav** [comment]
@vikaskumr did the suggestion from @chiubaka solve your issue?
